---
# Ceedling Project Configuration for PetSafe Cat Flap Firmware Testing

:project:
  :use_exceptions: FALSE
  :use_test_preprocessor: :none
  :use_auxiliary_dependencies: TRUE
  :build_root: build
  :test_file_prefix: test_
  :which_ceedling: gem
  :default_tasks:
    - test:all

:environment: []

:extension:
  :executable: .out

:paths:
  :test:
    - +:test 
  :source:
    - +:. # Source files in project root
  :include:
    - +:.
  :support:
    - test/support

# Exclude hardware-dependent source files that can't be easily tested
# These require full PIC16F886 hardware or comprehensive mocking
:files:
  :test:
    - +:test/test_*.c  # Only test_ prefixed files are tests
  :support:
    - +:test/support/xc_hardware_mock.c  # Support C files to compile
    - -:test/support/xc.h  # Don't try to compile header stubs
  :source:
    - -:cat.c         # Requires EEPROM functions
    - -:rfid.c        # Requires ADC and timer hardware
    - -:serial.c      # Requires UART hardware
    - -:peripherials.c # Requires full port manipulation
    - -:interrupts.c  # Requires interrupt hardware
    - -:user.c        # Requires initialization hardware
    - -:main.c        # Full application, tested via integration
    - -:configuration_bits.c # Hardware configuration only

:defines:
  :test:
    - _XTAL_FREQ=19660800UL
    - __XC8
    - TEST

:flags:
  :test:
    :compile:
      :*:
        - -std=c99
        - -Wall
        - -Wno-unused-parameter
        - -Wno-unused-function
        - -I.
        - -Itest/support

:plugins:
  :load_paths: []
  :enabled:
    - report_tests_pretty_stdout
    - module_generator
